# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 51c13111099f53ab4f79d2a5cb538236f058a21226e1b9e18c036898a7e7d7b1f715507979b386da9807cd3df5239882706d4059185c9bd95e501f37344a34bb

test:
  secret_key_base: 61216882d2a77def327211874aaeaeca059412ccb2ccef8b2e4f399199094a0ed76d66b19dc099e73897e327f2bc9d7bc7e37c8937ae025c410c62c802e4fb6e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
